package com.cryptoloan.contract.application;
import com.cryptoloan.contract.domain.model.ContractProof;import com.cryptoloan.contract.domain.port.out.ContractPorts.*;import java.math.BigDecimal;import java.nio.charset.StandardCharsets;import java.security.MessageDigest;import java.time.Instant;import java.util.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service public class ContractService{private final Repository contracts;private final DocumentStorage documents;private final BlockchainSignature signatures;public ContractService(Repository c,DocumentStorage d,BlockchainSignature s){contracts=c;documents=d;signatures=s;}
 @Transactional public ContractProof generate(Long loanId,String email,BigDecimal amount,String symbol,BigDecimal collateral,BigDecimal minimumRatio){return contracts.find(loanId).orElseGet(()->{Instant generated=Instant.now();byte[] content=("CRYPTOLOAN — CONTRAT DE PRÊT GARANTI\nVersion: 1\nIdentifiant du prêt: "+loanId+"\nEmprunteur: "+email+"\nPrincipal: "+amount+" EUR\nGarantie: "+collateral+" "+symbol.toUpperCase()+"\nRatio minimal: "+minimumRatio+"\nDate de génération: "+generated+"\n\nCONDITIONS\n1. La garantie demeure affectée au remboursement du prêt.\n2. Une alerte est émise à l'approche du seuil configuré.\n3. Une valeur sous le ratio minimal déclenche la liquidation selon les règles de la plateforme.\n4. Les deux signatures électroniques et l'empreinte SHA-256 constituent la preuve technique de cette démonstration.\n5. Ce document de démonstration ne remplace pas un contrat validé par un conseil juridique.\n").getBytes(StandardCharsets.UTF_8);String reference=documents.store(loanId,content);return contracts.save(new ContractProof(loanId,email,sha256(content),null,null,reference,generated));});}
 public ContractProof get(Long id){return contracts.find(id).orElseThrow(()->new NoSuchElementException("Contrat introuvable"));}
 public byte[] document(Long id,String requester,boolean admin){ContractProof p=get(id);authorize(p,requester,admin);return documents.load(p.documentReference());}
 @Transactional public ContractProof signUser(Long id,String email){ContractProof p=get(id);authorize(p,email,false);return contracts.save(p.userSigned(signatures.sign(id,p.contractHashHex(),"user:"+email)));}
 @Transactional public ContractProof signAdmin(Long id){ContractProof p=get(id);return contracts.save(p.adminSigned(signatures.sign(id,p.contractHashHex(),"admin")));}
 private void authorize(ContractProof p,String requester,boolean admin){if(!admin&&!p.borrowerEmail().equalsIgnoreCase(requester))throw new SecurityException("Contrat d'un autre utilisateur");}
 static String sha256(byte[] data){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(data));}catch(Exception e){throw new IllegalStateException(e);}}
}
