package com.cryptoloan.loan.application;
import com.cryptoloan.loan.domain.model.*;import com.cryptoloan.loan.domain.port.out.LoanPorts.*;import java.math.*;import java.util.*;import org.springframework.beans.factory.annotation.Value;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service public class LoanService{private final Repository loans;private final PriceCatalog prices;private final ContractManagement contracts;private final Notifications notifications;private final Audit audit;private final BigDecimal defaultMinimum;private final BigDecimal warningRatio;
 public LoanService(Repository loans,PriceCatalog prices,ContractManagement contracts,Notifications notifications,Audit audit,@Value("${cryptoloan.liquidation.min-ratio}")BigDecimal minimum,@Value("${cryptoloan.liquidation.warning-ratio}")BigDecimal warning){this.loans=loans;this.prices=prices;this.contracts=contracts;this.notifications=notifications;this.audit=audit;this.defaultMinimum=minimum;this.warningRatio=warning;}
 @Transactional public Loan create(UUID requestId,String email,String name,BigDecimal amount,String symbol,BigDecimal collateral,BigDecimal minimum){Optional<Loan>existing=loans.findByRequestId(requestId);if(existing.isPresent())return existing.get();Loan saved=loans.save(Loan.create(requestId,email,name,amount,symbol,collateral,minimum==null?defaultMinimum:minimum));audit.record(email,"LOAN_CREATED","loan:"+saved.id(),"Montant="+amount+", garantie="+collateral+" "+symbol);notifications.send(email,"LOAN_CREATED","Demande de prêt reçue","Votre demande de prêt #"+saved.id()+" a été enregistrée.",saved.id());return saved;}
 public List<Loan>mine(String email){return loans.findByBorrower(email);}public List<Loan>all(){return loans.findAll();}public Loan get(Long id){return loans.findById(id).orElseThrow(()->new NoSuchElementException("Prêt introuvable"));}
 @Transactional public Loan approve(Long id,String admin){Loan loan=get(id);var contract=contracts.generate(loan);Loan saved=loans.save(loan.approve(contract.hash()));audit.record(admin,"LOAN_APPROVED","loan:"+id,"Contrat="+contract.hash());notifications.send(saved.borrowerEmail(),"LOAN_APPROVED","Prêt approuvé","Votre prêt #"+id+" est approuvé. Le contrat est disponible dans votre espace.",id);return saved;}
 @Transactional public void checkRisk(){for(Loan loan:loans.findActive())checkOne(loan);}
 private void checkOne(Loan loan){try{BigDecimal value=prices.eur(loan.collateralSymbol()).multiply(loan.collateralAmount());BigDecimal ratio=value.divide(loan.amountEur(),6,RoundingMode.HALF_UP);if(ratio.compareTo(loan.minimumRatio())<0){Loan liquidated=loans.save(loan.liquidate(ratio));audit.record("system","LOAN_LIQUIDATED","loan:"+loan.id(),"ratio="+ratio);notifications.send(liquidated.borrowerEmail(),"LOAN_LIQUIDATED","Liquidation du prêt","Le prêt #"+loan.id()+" a été liquidé. Ratio observé : "+ratio,loan.id());}else if(ratio.compareTo(warningRatio)<0&&!loan.warningSent()){loans.save(loan.warn(ratio));notifications.send(loan.borrowerEmail(),"LIQUIDATION_WARNING","Alerte de seuil de liquidation","Le ratio du prêt #"+loan.id()+" est de "+ratio+". Ajoutez une garantie pour éviter la liquidation.",loan.id());audit.record("system","LIQUIDATION_WARNING","loan:"+loan.id(),"ratio="+ratio);}else if(ratio.compareTo(warningRatio)>=0&&loan.warningSent())loans.save(loan.observeHealthy(ratio));else loans.save(loan.observe(ratio));}catch(RuntimeException e){audit.record("system","RISK_CHECK_FAILED","loan:"+loan.id(),e.getClass().getSimpleName());}}
}

